version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "MusicAnalyticsCluster"

  producer:
    image: python:3.8
    build:
      context: ./producer
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - ./producer:/app
    command: python producer.py

  consumer:
    image: python:3.8
    build:
      context: ./consumer
    depends_on:
      - kafka
      - cassandra
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      CASSANDRA_HOST: cassandra
    volumes:
      - ./consumer:/app
    command: python consumer.py

  dashboard:
    image: node:16
    build:
      context: ./dashboard
    volumes:
      - ./dashboard:/app
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"